### ISSUE TITLE
Compile error when g++ abi version less than 4

### ISSUE THREAD

**Issue by xsc351072127** [vectorclass/version1#2]
Hello.
When I use the version1 class lib with some old version gcc with -mavx2. I meet some compile error like these:

```
g++ -O3 -mavx2 -mfma -std=c++0x -c dispatch_example.cpp -od8.o
In file included from vectorclass.h:73:0,
                 from dispatch_example.cpp:36:
vectorf512e.h: In function ‘Vec16f reinterpret_f(const Vec512b&)’:
vectorf512e.h:1635:50: error: call of overloaded ‘reinterpret_f(Vec256b)’ is ambiguous
     return Vec16f(Vec8f(reinterpret_f(x.get_low())), Vec8f(reinterpret_f(x.get_high())));
                                                  ^
vectorf512e.h:1635:50: note: candidates are:
In file included from vectorclass.h:61:0,
                 from dispatch_example.cpp:36:
vectorf256.h:2193:23: note: __m256 reinterpret_f(const Vec32c&)
 static inline __m256  reinterpret_f (Vec32c const & x) {
                       ^
vectorf256.h:2197:23: note: __m256 reinterpret_f(const Vec16s&)
 static inline __m256  reinterpret_f (Vec16s const & x) {
```

My gcc version is old which defalt c++ abi version is 2:
```
gcc version 4.8.5 20150623 (Red Hat 4.8.5-28) (GCC)
-fabi-version=n
           Use version n of the C++ ABI.  The default is version 2.
```
I review the code in the class lib:

```
vectorf512e.h:1635
static inline Vec16f  reinterpret_f (Vec512b const & x) {
    return Vec16f(Vec8f(reinterpret_f(x.get_low())), Vec8f(reinterpret_f(x.get_high())));
}
```
Vec512b::get_low() will return a Vec256b vector.

The function signature in the vectorf256h is:
```
static inline __m256  reinterpret_f (Vec32c const & x)
static inline __m256  reinterpret_f (Vec16s const & x)
```

All of Vec32c and Vec16s are derived from Vec256b so the compile complained about those message.

So I do some patch like these and create these issue for you.

```
diff --git a/vectorf256.h b/vectorf256.h
index 5fdba45..fab8585 100644
--- a/vectorf256.h
+++ b/vectorf256.h
@@ -2190,19 +2190,7 @@ static inline __m256i reinterpret_i (Vec4d const & x) {
     return _mm256_castpd_si256(x);
 }

-static inline __m256  reinterpret_f (Vec32c const & x) {
-    return _mm256_castsi256_ps(x);
-}
-
-static inline __m256  reinterpret_f (Vec16s const & x) {
-    return _mm256_castsi256_ps(x);
-}
-
-static inline __m256  reinterpret_f (Vec8i const & x) {
-    return _mm256_castsi256_ps(x);
-}
-
-static inline __m256  reinterpret_f (Vec4q const & x) {
+static inline __m256  reinterpret_f (Vec256b const & x) {^M
     return _mm256_castsi256_ps(x);
 }

@@ -2214,19 +2202,7 @@ static inline __m256  reinterpret_f (Vec4d const & x) {
     return _mm256_castpd_ps(x);
 }

-static inline __m256d reinterpret_d (Vec32c const & x) {
-    return _mm256_castsi256_pd(x);
-}
-
-static inline __m256d reinterpret_d (Vec16s const & x) {
-    return _mm256_castsi256_pd(x);
-}
-
-static inline __m256d reinterpret_d (Vec8i const & x) {
-    return _mm256_castsi256_pd(x);
-}
-
-static inline __m256d reinterpret_d (Vec4q const & x) {
+static inline __m256d reinterpret_d (Vec256b const & x) {^M
     return _mm256_castsi256_pd(x);
 }

```

**Comment by AgnerF** [comment]
Gcc ABI version 2 does not work with __m256 etc. 

Perhaps it works if you 
#define MAX_VECTOR_SIZE 128

Anyway, it is not recommended to use old compiler versions. Please use the latest version of the vector class library and the latest version of the Gcc or Clang compiler.

**Comment by xsc351072127** [comment]
These is a macro in the vectorf256.h
```
#if !defined (GCC_VERSION) || (defined (__GXX_ABI_VERSION) && __GXX_ABI_VERSION >= 1004)
balabala....
#else  // __GXX_ABI_VERSION < 1004
balabala....
static inline __m256d reinterpret_d (Vec32c const & x)；
static inline __m256d reinterpret_d (Vec16s const & x);
#endif  // __GXX_ABI_VERSION
```
Any compiler use c++ abi version 2 and with -mavx2 will get a comile error.
I just think those code was not right because when call reinterpret_f(Vec256b), from  vectorf512e.h:1635, the function signature is ambiguous ,in the vectorf256.h:2167 means that __GXX_ABI_VERSION < 1004.

**Comment by AgnerF** [comment]
I am not sure what you mean. Should it just issue an error message when ABI version < 4 rather than attempt to work around it?

**Comment by xsc351072127** [comment]
I think it should be work around. But now when use workaround would get a compile error. Any version gcc do such like these:
g++ -O3 -fabi-version=3 -mavx2 -mfma -std=c++0x -c dispatch_example.cpp -od8.o

I think may be add some function signature "static inline __m256d reinterpret_d (Vec256b const & x)"
and "static inline __m256  reinterpret_f (Vec256b const & x)" to the vectorf256.h of "__GXX_ABI_VERSION < 1004"
branch may be a good idea to solve the problam.   (We need a function signature use “Vec256b” as parameter.)

Because in "vectorf512e.h:1635" call "reinterpret_f(x.get_low()))" which call some thing like reinterpret_d (Vec256b ), but now only have  reinterpret_f (Vec32c),reinterpret_f (Vec16s), they are ambiguous when call reinterpret_d (Vec256b).

Any way this just a very small issue,thanks your time to response.

**Comment by xsc351072127** [comment]
I think it should be work around. But now when use workaround would get a compile error. Any version gcc do such like these:
g++ -O3 -fabi-version=3 -mavx2 -mfma -std=c++0x -c dispatch_example.cpp -od8.o

I think may be add some function signature "static inline __m256d reinterpret_d (Vec256b const & x)"
and "static inline __m256  reinterpret_f (Vec256b const & x)" to the vectorf256.h of "__GXX_ABI_VERSION < 1004"
branch may be a good idea to solve the problam. 
Because in "vectorf512e.h:1635" call "reinterpret_f(x.get_low()))" which call some thing like reinterpret_d (Vec256b ), but now only have  reinterpret_f (Vec32c),reinterpret_f (Vec16s), they are ambiguous.

Any way this just a very small issue,thanks your time to response.

**Comment by AgnerF** [comment]
I have now added an error message. No need to do more because people should use version 2 anyway.
