### ISSUE TITLE
vector3d.h: no suitable conversion function from "Vec4fb" to "uint8_t={unsigned char}" exists

### ISSUE THREAD

**Issue by akbwyfc** [vectorclass/version1#3]
Hi all

I'm using the vectorclass for vlasitor software.

There is extra vector3d.h file to be added:
https://github.com/fmihpc/vlasiator/wiki/Installing-Vlasiator#vectorclass

when I compile the program I receive error relating vector3d.h file:
(I use intel compiler):
CC  -O3   -funroll-loops -std=c++17 -fopenmp -W -Wall -Wno-unused -Wno-unused-parameter -Wno-missing-braces -fabi-version=0 -mavx -DUSE_JEMALLOC -DJEMALLOC_NO_DEMANGLE   -DUSE_JEMALLOC -DJEMALLOC_NO_DEMANGLE -DPROFILE -DNDEBUG -DACC_SEMILAG_PQM -DTRANS_SEMILAG_PPM  -I/work/libraries/../phiprof-master/include  -I/work/libraries/jemalloc/include  -DDP  -DSPF -DVEC8F_AGNER  -ffast-math -c sysboundary/ionosphere.cpp -I/work/libraries/include -I/work/libraries/include -I/opt/cray/pe/trilinos/12.10.1.2/INTEL/16.0/x86_64/include -L/opt/cray/pe/trilinos/12.10.1.2/INTEL/16.0/x86_64/lib -lboost_program_options -I/work/libraries/Eigen -I/work/libraries/../version1-master -Wno-comment
In file included from sysboundary/ionosphere.cpp(42):
/work/libraries/../version1-master/vector3d.h(166): error: no suitable conversion function from "Vec4fb" to "uint8_t={unsigned char}" exists
      return (uint8_t(t1) & 7) == 7;
                      ^

In file included from sysboundary/ionosphere.cpp(42):
/work/libraries/../version1-master/vector3d.h(177): error: no suitable conversion function from "Vec4fb" to "uint8_t={unsigned char}" exists
      return (uint8_t(t1) & 7) != 0;
                      ^

In file included from sysboundary/ionosphere.cpp(42):
/work/libraries/../version1-master/vector3d.h(414): error: no suitable conversion function from "Vec4db" to "uint8_t={unsigned char}" exists
      return (uint8_t(t1) & 7) == 7;
                      ^

In file included from sysboundary/ionosphere.cpp(42):
/work/libraries/../version1-master/vector3d.h(430): error: no suitable conversion function from "Vec4db" to "uint8_t={unsigned char}" exists
      return (uint8_t(t1) & 7) != 0;
                      ^

sysboundary/ionosphere.cpp(3753): error: more than one instance of constructor "Vec3Dd::Vec3Dd" matches the argument list:
            function "Vec3Dd::Vec3Dd(__m256d)"
            function "Vec3Dd::Vec3Dd(Vec3Dd &&)"
            argument types are: ({...})
           Vec3d E({
                   ^

sysboundary/ionosphere.cpp(3757): error: more than one instance of constructor "Vec3Dd::Vec3Dd" matches the argument list:
            function "Vec3Dd::Vec3Dd(__m256d)"
            function "Vec3Dd::Vec3Dd(Vec3Dd &&)"
            argument types are: ({...})
           Vec3d B({
                   ^

sysboundary/ionosphere.cpp(4087): warning #1224: #warning directive: TODO: add SpatialCell::getVelocityBlockMinValue() in place of sparseMinValue ? (if applicable)
           #warning TODO: add SpatialCell::getVelocityBlockMinValue() in place of sparseMinValue ? (if applicable)
            ^

sysboundary/../readparameters.h(71): error: expected a "("
           if constexpr (std::is_floating_point_v<T>) {
              ^

sysboundary/../readparameters.h(71): error: namespace "std" has no member "is_floating_point_v"
           if constexpr (std::is_floating_point_v<T>) {
                              ^

sysboundary/../readparameters.h(71): error: type name is not allowed
           if constexpr (std::is_floating_point_v<T>) {
                                                  ^

sysboundary/../readparameters.h(71): error: expected an expression
           if constexpr (std::is_floating_point_v<T>) {
                                                    ^

compilation aborted for sysboundary/ionosphere.cpp (code 2)
Makefile:278: recipe for target 'ionosphere.o' failed
make: *** [ionosphere.o] Error 2

Cheers

**Comment by AgnerF** [comment]
It seems that you are using version 1 of vectorclass. vector3d.h is compatible only with version 2.
It should be possible to compile version 2 because you have -std=c++17.

**Comment by akbwyfc** [comment]
Thanks @AgnerF, I think my problem resolved using version2.

Cheers
